version: '3.8'

services:

  wiredcraft:
    container_name: wiredcraft
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - mongo-compose-network

  mongodb:
    image: mongo:latest
    container_name: mongo-dev-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network
    volumes:
      - mongo-db:/data/db
    restart: always

volumes:
  mongo-db:

networks:
  mongo-compose-network:
